-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 17:11:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pi_dev
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema we_manage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema we_manage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User_stories_bp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_stories_bp` (
  `id_User_stories_bp` INT NOT NULL,
  `user_story_bp` VARCHAR(45) NULL,
  `priority_bp` VARCHAR(45) NULL,
  PRIMARY KEY (`id_User_stories_bp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Features` (
  `id_Features` INT NOT NULL,
  `liste_user_story_bp` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Features`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Backlog_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Backlog_produit` (
  `id_Backlog_produit` INT NOT NULL,
  `liste_features_bp` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Backlog_produit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review_po`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review_po` (
  `id_review_po` INT NOT NULL,
  `id_po` INT NULL,
  `id_sprint` INT NULL,
  `description_po` VARCHAR(45) NULL,
  `etat` INT NULL,
  PRIMARY KEY (`id_review_po`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avancement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avancement` (
  `id_avancement` INT NOT NULL,
  `id_sprint` INT NULL,
  `id_tache` INT NULL,
  `id_projet` INT NULL,
  PRIMARY KEY (`id_avancement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`absence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`absence` (
  `id_absence` INT NOT NULL,
  `id_personnel` INT NULL,
  `date_conge` DATE NULL,
  `heure_conge` TIME NULL,
  `nbre_absence` INT NULL,
  PRIMARY KEY (`id_absence`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resolution_conflit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resolution_conflit` (
  `id_resolution_conflit` INT NOT NULL,
  `id_equipe` INT NULL,
  `id_conflit` INT NULL,
  `id_sm` INT NULL,
  `description_resolution_conflit` VARCHAR(45) NULL,
  `id_bs` INT NULL,
  PRIMARY KEY (`id_resolution_conflit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`burndownchart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`burndownchart` (
  `id_burndownchart` INT NOT NULL,
  `description_bdc` VARCHAR(45) NULL,
  `id_bp` INT NULL,
  `id_bs` INT NULL,
  PRIMARY KEY (`id_burndownchart`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_story_bs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_story_bs` (
  `id_user_story_bs` INT NOT NULL,
  `id_sprint` INT NULL,
  `description_user_story_bs` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user_story_bs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`backlog_sprint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`backlog_sprint` (
  `id_bs` INT NOT NULL,
  `id_equipe` INT NULL,
  `id_sm` INT NULL,
  `id_projet` INT NULL,
  `liste_sprint` VARCHAR(45) NULL,
  PRIMARY KEY (`id_bs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conflit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conflit` (
  `id_conflit` INT NOT NULL,
  `conflitcol` VARCHAR(45) NULL,
  `id_equipe` INT NULL,
  `id_sm` INT NULL,
  `description_conflit` VARCHAR(45) NULL,
  `id_bs` INT NULL,
  `etat_conflit` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_conflit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documentation` (
  `id_documentation` INT NOT NULL,
  `nom_documentation` VARCHAR(45) NULL,
  `contenu_documentation` VARCHAR(45) NULL,
  PRIMARY KEY (`id_documentation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calendrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calendrier` (
  `id_calendrier` INT NOT NULL,
  `liste_id_projets` VARCHAR(45) NULL,
  `liste_id_reunions` VARCHAR(45) NULL,
  PRIMARY KEY (`id_calendrier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`daily_meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`daily_meeting` (
  `id_daily_meeting` INT NOT NULL,
  `heure` TIME NULL,
  `duree_meeting` INT NULL,
  `id_equipe` INT NULL,
  `remaque` VARCHAR(45) NULL,
  PRIMARY KEY (`id_daily_meeting`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tableau_blanc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tableau_blanc` (
  `id_tableau_blanc` INT NOT NULL,
  `id_projet` INT NULL,
  `id_equipe` INT NULL,
  `id_sprint` INT NULL,
  PRIMARY KEY (`id_tableau_blanc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ligne_tab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ligne_tab` (
  `id_ligne_tab` INT NOT NULL,
  `id_tableau_blanc` INT NULL,
  `id_personnel` INT NULL,
  `nom_tache` VARCHAR(45) NULL,
  `etat_tache` VARCHAR(45) NULL,
  `date_ajout_ligne` DATETIME NULL,
  PRIMARY KEY (`id_ligne_tab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sprint_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sprint_review` (
  `id_sprint_review` INT NOT NULL,
  `id_sprint` INT NULL,
  `id_equipe` INT NULL,
  `id_projet` INT NULL,
  `remarque_sprint_review` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sprint_review`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sprint_retrospective`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sprint_retrospective` (
  `id_sprint_retrospective` INT NOT NULL,
  `id_sprint+1` INT NULL,
  `id_equipe` INT NULL,
  `id_projet` INT NULL,
  `descripion_TODO` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sprint_retrospective`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`forum` (
  `id_forum` INT NOT NULL,
  `id_projet` INT NULL,
  `id_equipe` INT NULL,
  PRIMARY KEY (`id_forum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `id_question` INT NOT NULL,
  `id_forum` INT NULL,
  `id_personnel` INT NULL,
  `image_question` VARCHAR(45) NULL,
  `text_question` VARCHAR(45) NULL,
  `nbr_like` INT NULL,
  PRIMARY KEY (`id_question`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`like` (
  `id_like` INT NOT NULL,
  `id_personnel` INT NULL,
  `like_etat` INT NULL,
  PRIMARY KEY (`id_like`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reponse` (
  `id_reponse` INT NOT NULL,
  `id_question` INT NULL,
  `image_reponser` VARCHAR(45) NULL,
  `nbr_up` INT NULL,
  `nbr_down` INT NULL,
  PRIMARY KEY (`id_reponse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`up_down`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`up_down` (
  `id_up_down` INT NOT NULL,
  `id_personnel` INT NULL,
  `id_reponse` INT NULL,
  `up` INT NULL,
  `down` VARCHAR(45) NULL DEFAULT 0,
  PRIMARY KEY (`id_up_down`))
ENGINE = InnoDB;

USE `we_manage` ;

-- -----------------------------------------------------
-- Table `we_manage`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT(11) NOT NULL,
  `Nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `Date_Naissance` VARCHAR(45) NULL DEFAULT NULL,
  `Numero_Tel` INT(11) NULL DEFAULT NULL,
  `UID` INT(11) NULL DEFAULT '0',
  `E-mail` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `User_name` VARCHAR(45) NULL DEFAULT NULL,
  `mot_de_passe` VARCHAR(45) NULL DEFAULT NULL,
  `Image_user` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`project_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_manager` (
  `id` INT(11) NOT NULL,
  `Nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `Date_Naissance` VARCHAR(45) NULL DEFAULT NULL,
  `Numero_Tel` INT(11) NULL DEFAULT NULL,
  `UID` INT(11) NULL DEFAULT '1',
  `E-mail` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `User_name` VARCHAR(45) NULL DEFAULT NULL,
  `mot_de_passe` VARCHAR(45) NULL DEFAULT NULL,
  `Image_user` VARCHAR(45) NULL DEFAULT NULL,
  `id_projet1` VARCHAR(45) NULL DEFAULT NULL,
  `id_projet2` VARCHAR(45) NULL DEFAULT NULL,
  `id_projet3` VARCHAR(45) NULL DEFAULT NULL,
  `Max_projet` VARCHAR(45) NULL DEFAULT '0',
  `Salaire` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_manager_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT(11) NOT NULL,
  `Nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `Date_Naissance` VARCHAR(45) NULL DEFAULT NULL,
  `Numero_Tel` INT(11) NULL DEFAULT NULL,
  `UID` INT(11) NULL DEFAULT '0',
  `E-mail` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `User_name` VARCHAR(45) NULL DEFAULT NULL,
  `mot_de_passe` VARCHAR(45) NULL DEFAULT NULL,
  `Image_user` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `admin_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`project_manager` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id_Client_default` INT(11) NOT NULL,
  `Nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `Date_Naissance` VARCHAR(45) NULL DEFAULT NULL,
  `Numero_Tel` INT(11) NULL DEFAULT NULL,
  `UID` INT(11) NULL DEFAULT '4',
  `E-mail` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `User_name` VARCHAR(45) NULL DEFAULT NULL,
  `mot_de_passe` VARCHAR(45) NULL DEFAULT NULL,
  `Image_user` VARCHAR(45) NULL DEFAULT NULL,
  `Pts_f` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Client_default`),
  CONSTRAINT `client_ibfk_1`
    FOREIGN KEY (`id_Client_default`)
    REFERENCES `mydb`.`admin` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`client_projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client_projet` (
  `id_Client` INT(11) NOT NULL,
  `Nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `Date_Naissance` VARCHAR(45) NULL DEFAULT NULL,
  `Numero_Tel` INT(11) NULL DEFAULT NULL,
  `UID` INT(11) NULL DEFAULT '3',
  `E-mail` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `User_name` VARCHAR(45) NULL DEFAULT NULL,
  `mot_de_passe` VARCHAR(45) NULL DEFAULT NULL,
  `Image_user` VARCHAR(45) NULL DEFAULT NULL,
  `id_projet` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Client`),
  CONSTRAINT `client_projet_ibfk_1`
    FOREIGN KEY (`id_Client`)
    REFERENCES `mydb`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`conge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conge` (
  `id_Conge` INT(11) NOT NULL,
  `date_debut_conge` DATE NULL DEFAULT NULL,
  `date_fin_conge` DATE NULL DEFAULT NULL,
  `id_personnel` INT(11) NULL DEFAULT NULL,
  `description_conge` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Conge`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`documentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documentation` (
  `id_Documentation` INT(11) NOT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `titre` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `id_project_manager` VARCHAR(45) NULL DEFAULT NULL,
  `date_document` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_Documentation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipes` (
  `id_equipe` INT(11) NOT NULL,
  `id_projet` INT(11) NULL DEFAULT NULL,
  `id_po` INT NULL DEFAULT NULL,
  `id_sm` INT NULL,
  `liste_personnel_equipe` VARCHAR(45) NULL,
  PRIMARY KEY (`id_equipe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formation` (
  `id_formation` INT(11) NOT NULL,
  `sujet_formation` VARCHAR(45) NULL,
  `id_equipe` INT NULL,
  `date_time_debut` DATETIME NULL,
  `date_time_fin` DATETIME NULL,
  `nom_formation` VARCHAR(45) NULL,
  PRIMARY KEY (`id_formation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`intervention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`intervention` (
  `id_intervention` INT(11) NOT NULL,
  `id_sm` INT(11) NULL DEFAULT NULL,
  `decription_intervention` VARCHAR(45) NULL DEFAULT NULL,
  `date_intevention` DATE NULL DEFAULT NULL,
  `id_reclamation` VARCHAR(45) NULL,
  PRIMARY KEY (`id_intervention`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personnel` (
  `id_Personnel` INT(11) NOT NULL,
  `Nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `Date_Naissance` VARCHAR(45) NULL DEFAULT NULL,
  `Numero_Tel` INT(11) NULL DEFAULT NULL,
  `UID` INT(11) NULL DEFAULT '2',
  `E-mail` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `User_name` VARCHAR(45) NULL DEFAULT NULL,
  `mot_de_passe` VARCHAR(45) NULL DEFAULT NULL,
  `Image_user` VARCHAR(45) NULL DEFAULT NULL,
  `Specialite` VARCHAR(45) NULL DEFAULT NULL,
  `ide_note` VARCHAR(45) NULL DEFAULT NULL,
  `ide_profil` VARCHAR(45) NULL DEFAULT NULL,
  `salaire` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Personnel`),
  CONSTRAINT `personnel_ibfk_1`
    FOREIGN KEY (`id_Personnel`)
    REFERENCES `mydb`.`project_manager` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`profil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profil` (
  `id_Profil` INT(11) NOT NULL,
  `id_Personnel` INT(11) NULL DEFAULT NULL,
  `Description_profil` VARCHAR(45) NULL DEFAULT NULL,
  `projet_realise` VARCHAR(45) NULL DEFAULT NULL,
  `experience` VARCHAR(45) NULL DEFAULT NULL,
  `anciente` VARCHAR(45) NULL DEFAULT NULL,
  `note_globale` VARCHAR(45) NULL DEFAULT NULL,
  `reclamations_profil` VARCHAR(45) NULL DEFAULT NULL,
  `specialite_sous_spec` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Profil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projet` (
  `id_projet` INT(11) NOT NULL,
  `id_po` INT(11) NULL DEFAULT NULL,
  `nom_projet` VARCHAR(45) NULL DEFAULT NULL,
  `date_debut_projet` DATE NULL DEFAULT NULL,
  `date_fin_projet` DATE NULL DEFAULT NULL,
  `etat_projet` INT(11) NULL DEFAULT NULL,
  `Description_projet` LONGTEXT NULL DEFAULT NULL,
  `id_equipe` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_projet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`reclamation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reclamation` (
  `id_reclamation` INT(11) NOT NULL,
  `id_personnel` INT(11) NULL DEFAULT NULL,
  `sujet_reclamation` VARCHAR(45) NULL DEFAULT NULL,
  `etat_reclamation` INT(11) NULL DEFAULT NULL,
  `description_reclamation` VARCHAR(45) NULL,
  PRIMARY KEY (`id_reclamation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`sprint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sprint` (
  `id_sprint` INT(11) NOT NULL,
  `date_debut_sprint` DATE NULL DEFAULT NULL,
  `date_fin_sprint` DATE NULL DEFAULT NULL,
  `liste_user_sroty_bs` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sprint`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `we_manage`.`tache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tache` (
  `id_Tache` INT(11) NOT NULL,
  `id_Sprint` VARCHAR(45) NULL DEFAULT NULL,
  `date_debut_tache` DATE NULL DEFAULT NULL,
  `date_fin_tache` DATE NULL DEFAULT NULL,
  `nom_tache` VARCHAR(45) NULL DEFAULT NULL,
  `type_tache` VARCHAR(45) NULL DEFAULT NULL,
  `liste_Personnel` INT(11) NULL DEFAULT NULL,
  `description_tache` VARCHAR(45) NULL DEFAULT NULL,
  `liste_nbre_heure` VARCHAR(45) NULL,
  `moyenne_estimation` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Tache`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
