bs_homepage:
    path:     /index
    defaults: { _controller: BSBundle:Default:index }
test:
    path:     /test
    defaults: { _controller: BSBundle:BacklogS:afficherp }

test_delete:
    path:     /deletebs/{id}
    defaults: { _controller: BSBundle:BacklogS:deletebs }

test_update:
    path:     /test1/{id}/{nbr}
    defaults: { _controller: BSBundle:BacklogS:updatebs }

Sprintv:
    path:     /sprintv
    defaults: { _controller: BSBundle:Sprint:create }

sprint_update:
    path:     /Sprintv1/{id}
    defaults: { _controller: BSBundle:Sprint:update }

sprint_delete:
    path:     /Sprintv/{id}
    defaults: { _controller: BSBundle:Sprint:delete }

Sprint_add:
    path:     /create
    defaults: { _controller: BSBundle:Sprint:create }
test1:
    path:     /add2
    defaults: { _controller: BSBundle:BacklogS:create }

test2:
    path:     /add3
    defaults: { _controller: BSBundle:BacklogS:add4 }

ajout:
    path:     /ajouter
    defaults: { _controller: BSBundle:BacklogS:add4 }

modifier:
    path:     /modifier
    defaults: { _controller: BSBundle:BacklogS:modif }

test4:
    path:     /ajouter
    defaults: { _controller: BSBundle:BacklogS:ajouter }

user_story:
    path:     /Userstory
    defaults: { _controller: BSBundle:Userst:affi }

user_story_add:
    path:     /aaa
    defaults: { _controller: BSBundle:Userst:add5 }

user_story_update:
    path:     /Userstory1/{id}/{desc1}/{desc2}
    defaults: { _controller: BSBundle:Userst:updateus }

modifier_us:
    path:     /modifier_us
    defaults: { _controller: BSBundle:Userst:update }

delete_us:
    path:     /delete_us/{id}
    defaults: { _controller: BSBundle:Userst:delete }

go_tache:
    path:     /tache/{id}
    defaults: { _controller: BSBundle:Tache:home }

ajout_tache:
    path:     /ajoutertache
    defaults: { _controller: BSBundle:Tache:add }

opa:
    path:     /opa
    defaults: { _controller: BSBundle:Tache:opa }

aff_tache:
    path:     /aff_tache
    defaults: { _controller: BSBundle:Tache:aff }
